name: Dependency Scanning

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'bun.lockb'
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'bun.lockb'
  workflow_dispatch:

jobs:
  scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.16
      
      - name: Install dependencies
        run: bun install
      
      - name: Run Bun audit
        run: bun audit || true
      
      - name: Setup Node.js for additional tools
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install audit tools
        run: npm install -g audit-ci
      
      - name: Run audit-ci
        run: audit-ci --config ./audit-ci.json || true
        continue-on-error: true