name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kontainers_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.16
      
      - name: Install dependencies
        run: bun install
      
      - name: Run linting
        run: bun run lint
      
      - name: Run unit tests
        run: bun test:unit
      
      - name: Run smoke tests
        run: bun test:smoke
      
      - name: Run performance tests
        run: bun test:performance
      
      - name: Run integration tests
        run: bun test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kontainers_test
      
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
      
      - name: Run Playwright tests
        run: bunx playwright test
        env:
          CI: true
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Run comprehensive test suite
        run: bun run test:comprehensive
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/kontainers_test